version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: open_audit
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: openaudit@123
      POSTGRES_DB: open_audit
    ports:
      - "5433:5432"
    volumes:
      - ./infra/init.sql:/docker-entrypoint-initdb.d/init.sql